# Generated by Django 4.1.2 on 2022-11-26 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField()),
                ('version', models.CharField(max_length=10)),
                ('prix', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('domaine', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('date_archive', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('profession', models.CharField(max_length=100)),
                ('nb_tests', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('nb_formation', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=10)),
                ('prix', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('HARD SKILLS', 'HARD SKILLS'), ('SOFT SKILLS', 'SOFT SKILLS')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResultTestArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=20)),
                ('date_effectue', models.DateTimeField(auto_now_add=True)),
                ('condidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.condidat')),
                ('test_effectue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.archive')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=20)),
                ('date_effectue', models.DateTimeField(auto_now_add=True)),
                ('condidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.condidat')),
                ('test_effectue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.test')),
            ],
        ),
        migrations.CreateModel(
            name='QuizArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.archive')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.test')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('prix', models.CharField(max_length=255)),
                ('nb_participants', models.CharField(max_length=20)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employment.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('certif', models.FileField(upload_to='media/certif/')),
                ('formation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employment.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=50)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.domaine')),
            ],
        ),
        migrations.CreateModel(
            name='AssociatDomaineParCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.category')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.domaine')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.test')),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='id_test_archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.test'),
        ),
    ]
