# Generated by Django 4.1.2 on 2022-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_remove_category_domaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatdomaineparcategory',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
