# Generated by Django 4.1.2 on 2022-11-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_alter_associatdomaineparcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatdomaineparcategory',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employment.test'),
        ),
    ]
