# Generated by Django 4.1.2 on 2022-11-27 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_alter_associatdomaineparcategory_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssociatDomaineFormationParCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.domaineformation')),
                ('formation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employment.formation')),
            ],
        ),
    ]
