# Generated by Django 4.1.2 on 2022-11-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_domaineformation_associatdomaineformationparcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatdomaineparcategory',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm', to='employment.domaine'),
        ),
        migrations.AlterField(
            model_name='associatdomaineparcategory',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tst', to='employment.test'),
        ),
    ]
