# Generated by Django 4.1.2 on 2022-11-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_alter_associatdomaineparcategory_domaine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='form_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
