# Generated by Django 4.1.2 on 2022-11-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0007_quiz_form_name_quiz_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='form_name',
            new_name='radio_name',
        ),
    ]
